os:
  - osx
  - linux

language: rust
rust:
  - stable
  - beta
  - nightly

before_install:
  - unxz -k hfsp-blank.img.xz
  - unxz -k hfsp-small.img.xz
  - unxz -k hfsp-many2.img.xz

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

addons:
  apt:
    packages:
      - libfuse-dev
  homebrew:
    casks:
      - osxfuse
